FROM node:20.9.0-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Run the app
FROM node:20.9.0-alpine AS runner
WORKDIR /app

COPY --from=builder /app/.next .next
COPY --from=builder /app/public public
COPY --from=builder /app/package.json .
COPY --from=builder /app/next.config.ts .
COPY --from=builder /app/node_modules node_modules

CMD ["npm", "run", "start"]